### ISSUE TITLE
Missing ~/.st2/config for vagrant when using Vagrant

### ISSUE THREAD

**Issue by Heshuge** [StackStorm/st2#1932]
root@st2express:/opt/stackstorm/packs# ls ~/.st2/
config  token
root@st2express:/opt/stackstorm/packs# exit
exit
vagrant@st2express:/opt/stackstorm/packs$ ls ~/.st2/
ls: cannot access /home/vagrant/.st2/: No such file or directory

**Comment by Kami** [comment]
We've discussed this on our private Slack and right now, this is a feature and works as intended.

On installation, inside st2_deploy.sh, we write CLI config file with a default set of credentials for a root user under which the deploy script runs (that's a feature).

If you use CLI as another user, config won't be available which means you need to explicitly provide all the information it needs to connect to the StackStorm installation (base url, credentials) if StackStorm services are not running on the same server (if they are running on the same server, you only need to provide the credentials since it will assume a value of "localhost").

One option we discussed is writing a default config if one doesn't exist yet when the user invokes the CLI - this would make it easier to get started (if user wants to connect to a different installation they can now simply edit the existing config and they don't need to Google for the default config, copy that in and replace the values...).

Keep in mind that because of the security and "portability" reasons we would only write down the default values for the ``base_url`` option (localhost) which tell it where StackStorm is running. We wouldn't not write the credentials (for one, CLI is not and should not be aware of the default credentials - only st2_deploy.sh and installer are aware of that and they write this information in the config for the root user).
