### ISSUE TITLE
Need to decouple binaries from st2common component

### ISSUE THREAD

**Issue by dennybaa** [StackStorm/st2#1958]
When packages are shipped separately like st2actions or st2reactor, common binaries will fail to work.
Since in one case it will fail to load sensor specific modules and in the second case actions specific..

http://drone.vos.io/github.com/dennybaa/st2-packages/master/97fd4f2a41777c7517ea201d7a9277f6741ddda4

Details:  https://gist.github.com/dennybaa/9fe10027a8eb167a7e0b

**Comment by Kami** [comment]
Yep, as discussed on slack we should simply move all the "registrar" modules to st2common package.

I was a bit worried at first that the registrar code is too coupled to the corresponding component, but I checked it out and it looks like that moving everything to st2common package shouldn't be too bad since it's actually not that coupled :)

**Comment by dennybaa** [comment]
sounds good:)

**Comment by dennybaa** [comment]
PS. for the begging st2-register-content is important, but others binaries also might be a problem in future.

**Comment by Kami** [comment]
@dennybaa Do you have anything specific in mind? `st2-submit-debug-info` should not be problematic since we can (and should) simply install st2debug on every server.

I guess one which might be problematic is the rule tester and trigger refire. But those are (intentionally) coupled to the corresponding component and not much we can do there.

**Comment by dennybaa** [comment]
I see only one another binary `bin/st2-bootstrap-rmq` which might not work. Other stuff is component specific as you said... and consequently it works.

**Comment by Kami** [comment]
Yeah, `st2-bootstrap-rm` is a utility which is not really used right now  (we execute same piece of code on every service startup) so this shouldn't be a big deal right now.

**Comment by dennybaa** [comment]
than we can deprecate this utility, would be nice...
