### ISSUE TITLE
Feature request - Ability to embed tests into a pack

### ISSUE THREAD

**Issue by tonybaloney** [StackStorm/st2#2056]
Want the ability to include tests in my custom packs, and have tests for the st2contrib packs.

This is especially relevant for sensors, when writing sensors you have to constantly install, test, patch, install, patch.

It would be great if you could have tested your actions and sensors before loading them onto a server.

Pack layout could be
* actions/
* sensors/
* tests/
* tests/test_actions.py
* tests/test_sensors.py

Then some base classes

ActionUnitTest
- LoadAction(name)
- RunAction (name, **kwargs)

Same for sensors, ability to mock out back end APIs (possibly having a different requirements.txt file for testing (e.g test-requirements.txt)

**Comment by tonybaloney** [comment]
This is becoming more and more important as our packs become more complex, also the ability to validate mistral workflow syntax before installing the pack. 
Any thoughts on this?

**Comment by Kami** [comment]
We don't have an ETA yet since we are still busy working on some other high priority items (related to scale and better supportability).

In any case, `pack/<resource>/tests/` for particular resource tests and `pack/tests/` for "global" pack tests convention seems reasonable.

`requirements-test.txt` convention seems reasonable as well, but I imagine this shouldn't be needed in most cases since we should install and make libraries such as unittest2, mock, etc. available to all the tests by default.

As far as mock sensor service and other mock classes (runner, etc.) go - this needs a bit more thought, but feel free to start working on the tests itself and eventually when we add more support for resource testing to StackStork you can utilize those new features / class.

**Comment by tonybaloney** [comment]
this is done now
