### ISSUE TITLE
Action names in flow editor get truncated

### ISSUE THREAD

**Issue by tonybaloney** [StackStorm/st2#2065]
If the pack name is long, then the action name is long, showing the items in flow truncates the names.

![image](https://cloud.githubusercontent.com/assets/1532417/10419516/a74bc1ba-70c5-11e5-916b-903865464c44.png)

Does the pack name really need to be shown at all? it's already being grouped by pack name, so the action name will suffice.

Also, having an English based action name will make things easier to read. For large packs (e.g. AWS) the reams of actions make it quite hard to navigate

**Comment by enykeev** [comment]
Thanks for the report!

IIRC, we decided to show action reference instead of action name to improve discoverability (if user looks for `core.local` action, it would be easier for him to spot it as a line line rather than a `local`name within `core` group half a screen away). With examples you've shown though, I agree with you, there's little point in having pack name inline when you can't differentiate between two actions. We'll see what we can do to fix that.

Another problem though is the fact we don't make enough effort to indicate the fact the overall UX of the system depends on pack metadata as much as on UI design choices. Simply having shorter names and descriptive descriptions can make a world of difference. AWS pack is a textbook example of the opposite.

**Comment by dzimine** [comment]
Yes, we'll do something with this in a next spin. Not showing pack names, cause they're already in the code. Collapsing the beginning, not the end... 
Once we fix the pack install and will support pack name != pack repo name, we will get 3 chars back :)

**Comment by enykeev** [comment]
We've just made the similar change to st2web so I guess our position on the issue have changed. I'll see the issue to get resolved in the next release.
