### ISSUE TITLE
Provide a reference to the kv datastore in Actions

### ISSUE THREAD

**Issue by devth** [StackStorm/st2#2195]
Accessing kv pairs should be easy from anywhere within the system, as it is currently in Rules using `{{system.os_keystone_endpoint}}`.

**Comment by lakshmi-kannan** [comment]
More concrete suggestion from devth was at least for python actions, the base class could wrap an interface to KV store.

**Comment by Kami** [comment]
So something similar as we do for sensors? I'm not against that for Python runner actions as long as we document "good" and "bad" patterns in the documentation.

We had a similar, but more broad feature request in the past (allowing user to reference key value items in the metadata), but I was against that since it breaks "even driven actions" pattern - ideally you should pass parameters to actions instead of referencing stuff inside the metadata / action. Passing parameters to the actions makes actions more re-usable, easier to test, etc. (think dependency injection in programming languages).

I know this is not always possible and / or wanted, but for majority of the use cases, it's the right approach.

I will also try do dig out the old ticket since I provided more context there.
