### ISSUE TITLE
Feature request - Expose config.yaml in packs in the UI

### ISSUE THREAD

**Issue by tonybaloney** [StackStorm/st2#2196]
having to SSH to the stackstorm server to edit config.yaml is the last remaining task for an end-to-end deployment that requires Bash/SSH.

inside the actions window, could click on a configure icon next to the pack name (currently collapsible) then the properties for the pack action are loaded in the parameters window on the left for editing. 

Then a save feature.

Pretty please.

**Comment by manasdk** [comment]
That would be a nice feature indeed. 

We do need to think about the implications of exposing config this way so hopefully tight RBAC controls etc.

**Comment by dzimine** [comment]
Thanks Ant. Ack. On the roadmap.

**Comment by Kami** [comment]
+1

> We do need to think about the implications of exposing config this way so hopefully tight RBAC controls etc.

And also the whole content distribution story - this works fine for single server deployments, but it's a different story for multi server deployments.

Anyways, that's the part of the whole content distribution and sync story and exactly the same issue exists for other resources and pack content.

So not a blocker right now, but something we should (and plan to) address in the future.

**Comment by tonybaloney** [comment]
you could have a packs.configure action for a short-term fix where you pass the pack name and the desired configuration as a parameter. 
At least I can configure the pack without having local filesystem access then.

**Comment by Kami** [comment]
That's an interesting idea.

This could potentially work, we would just need to implement a custom YAML parser so we can preserve the original order and comments in the config.

**Comment by manasdk** [comment]
True, just an action. Could work :)

Preserving original order etc will require custom yaml parsing for sure and last I looked it was not trivial. Hopefully we can borrow heavily from existing parsers.

**Comment by tonybaloney** [comment]
In fact for now I'll just have a "configure" action in my pack that takes the configuration parameters and writes to the YAML file. Maybe that could be a convention?

**Comment by michaelansel** [comment]
Does that mean you are effectively self-modifying the code directory? Ewwwww. If we are trying to improve configuration, I would much prefer a standard way of defining configs in "the config place" (wherever that is) and only including defaults/examples in the code directory (which also matches what is committed to the pack repo).

**Comment by Kami** [comment]
@michaelansel That's correct.

Most of us are not big fans of that approach either since we preach and try to follow "infrastructure as code" approach everywhere (everything should be version controlered, etc.), but some of our users and customers have specific needs (and not everyone has fully transitioned to infra as code yet) and that's why we are adding some of that functionality.

We will also make sure that all the functionality which doesn't directly follow "infrastructure as code" approach is well documented and users are aware of the limitations / caveats.

Having said that, most of our advanced users do follow "infrastructure as code" approach and version control their packs directory, etc.

**Comment by michaelansel** [comment]
I'm pretty sure I understand the use case, but why not write the UI-managed configs to a dedicated location instead of modifying the actual pack directory? Then you don't need to deal with "don't overwrite the config" when you update a pack (which, for non-IaaC orgs is probably log in and git pull or pack.download, both of which would blow it away). Modifying the deployed code directory is what I'm particularly concerned about.

**Comment by enykeev** [comment]
We're going to release interactive configuration as a part of st2 cli tool in 2.1. That's not exactly what you're asking, but it should lift some pressure.

**Comment by LindsayHill** [comment]
As of ST2 2.4, you can install, delete & configure packs via the UI
