### ISSUE TITLE
WebUI or Mistral - pick which won't work, when external IP not reachable from inside the box

### ISSUE THREAD

**Issue by dzimine** [StackStorm/st2#2203]
Reported by @tonybaloney: 

he got internal and external IP address, and NAS. If mistral connects to internal api address as set up by . If so, WebUI can't connect to auth and API. And vice versa: if the API url is set to external IP address, Mistral can't connect to it because it's behind the NAT and not routable from within the box. 

In short, mistral needs to connect via internal ip, UI needs to connect to external IP/address, and we only have one URL parameter, the `api_url` in the `[auth]` section of `/etc/st2/st2.conf`

Temp workaround: via local /etc/hosts. 

@tonybaloney please add details if I missed smth. 

[stackstorm-community.slack.com link](https://stackstorm-community.slack.com/archives/community/p1447383434000310)

**Comment by Kami** [comment]
I'm +1 for having a special setting for API URL which is used by Mistral when talking back to the API.

In the past this was a big mess since we just used API listen IP and port and then we improved it by using a single value (public URL of the API endpoint).

Using public URL won't always work / is not always desired so having another setting is useful and makes sense.

We just need to make sure the setting has a good self explanatory name and we have good docs on it (`api_url` under `mistral` section seems reasonable to me).

**Comment by Kami** [comment]
Also, to clarify what @lakshmi-kannan and I discussed on Slack.

That's done to support typical multi-server deployments when you want to reduce the attack surface area. This means ideally Mistral (and other st2 components) would talk to st2 using an internal interface, ideally a separate VLAN.

So that's not just to support single box deployments, quite the contrary - it's there to support "traditional" multi-server setups and network configurations.

Anyway, security is a complex topics and trends are also changing with containers, etc. and I think such "traditional" networking setups will become obsolete in the future (they introduce a lot of unnecessary complexity, etc.).

In the future, I do think having every component talk to each other over the public interface is fine - public interface should be using SSL and all the other necessary security measures so using public interface shouldn't necessary reduce the security. It means same security for everyone (internal and external consumers).

I also think I read something about Google at some point doing something like that - treating all the internal traffic as external and using same security measures...

**Comment by Kami** [comment]
@tonybaloney Just a heads up, v1.1.1 which includes this change has been released - https://github.com/StackStorm/st2/releases/tag/v1.1.1

Official release announcement with more details will go out today.
