### ISSUE TITLE
Instructions on installing/using st2 behind a Proxy

### ISSUE THREAD

**Issue by armab** [StackStorm/st2#2244]
This seems to be more and more popular question/issue in community recent time.

We need separate doc, describing how to install st2 behind the proxy (have no idea if it's even possible for the moment).

**Comment by devth** [comment]
:+1: 

Running the all-in-one installer with `http_proxy` / `https_proxy` env vars set didn't work (it failed to grab github dependencies, and maybe other issues too).

I tried another approach: I ran the installer in a dev environment with no proxy, then created a snapshot of that image and created an instance in prod (where the proxy is required). This appeared to work at first, but I ran into issues. I opened the web UI and ran through `/setup`, setting hostname, user/password, then tried to finish the installation. The last step just said:

```
sudo: no tty present and no askpass program specified
```

I'm confused on why there needs to be a separate installation step - this makes it hard to do what I'm trying to do (create the snapshot that's ready to config/use in dev and run it in prod).

I then tried to login to the dashboard, but it continually errored with:

```
Invalid or missing credentials
```

So I ssh'd into the instance and checked the credentials at `/opt/puppet/hieradata/answers.json`, and they were correct.

Then:

- I manually set `system::http_proxy` in `/opt/puppet/hieradata/answers.json` but that doesn't seem to do much. 
- had to set
  ```[http] 
    proxy=...
  ```
  in /etc/gitconfig and that let `update-system` satisfy its git deps
- trying to figure out how to set env `http_proxy` for `update-system` or else it gets stuck on the step `Updating Debian apt-cache...`. I can't just edit /etc/sudoers to keep `http_proxy` because that file is managed by puppet and not under my control. I ran `sudo -s` and manually set `http_proxy`. That let it get past its `debian apt-cache` step. It looked like stuff succeeded.

```
Updating Debian apt-cache...
Setting up Puppet environments...
Warning: Facter: ldapname is deprecated and will be removed in a future version
Warning: Facter: Error loading fact /usr/lib/ruby/vendor_ruby/facter/macosx.rb: cannot load such file -- cfpropertylist
Warning: Facter: Facter::Util::EC2.has_euca_mac? is deprecated; see the Facter::EC2 classes instead
Warning: Facter: Facter::Util::EC2.has_openstack_mac? is deprecated; see the Facter::EC2 classes instead
Warning: Facter: Facter::Util::EC2.has_ec2_arp? is deprecated; see the Facter::EC2 classes instead
Notice: Compiled catalog for st2.foo.com in environment production in 17.08 seconds
Notice: Applied catalog in 5.42 seconds
```

Tried to login to the dashboard again but same problem:

```
Invalid or missing credentials
```

![no idea](https://media.giphy.com/media/xDQ3Oql1BN54c/giphy.gif)

**Comment by jfryman** [comment]
Thanks @devth! This investigation is very helpful! :bow:

We've setup a small proxy lab, and will be certifying Proxy support very soon! Will keep you updated as we fix/learn. 

In terms of two-step process... it is completely possible to bypass the two-phase install with the assistance of an Answer file. Take a look at https://docs.stackstorm.com/install/all_in_one.html#example-answers-file and see if that helps you get going in a more streamlined mechanism.

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/support/p1451931070001029

**Comment by armab** [comment]
https://docs.stackstorm.com/proxy.html
