### ISSUE TITLE
All-One-Installer should allow ChatOPS via external Bot without installing local hubot

### ISSUE THREAD

**Issue by jon-middleton** [StackStorm/st2#2285]
We are running our own version of hubot external to the StackStorm server, but it would be very nice if the All-in-Installer would allow the enabling of ChatOPS without install an local hubot into Dock.

The other option is supply some documentation on how to remove it from the system post installation, as puppet seems to be restoring the docker contain when stackstorm/hubot and it's images have been removed.

**Comment by jfryman** [comment]
@jon-middleton Thanks for the input! We've gone ahead and pushed https://github.com/StackStorm/st2workroom/issues/290. If you'd like some help getting an older version of Hubot uninstalled, let us know in our Community Room, and we'll gladly help you out. Otherwise, install clean and install away!

Cheers!
