### ISSUE TITLE
Feature request: Expose the hubot hipchat adapter settings 'rooms' and 'rooms_join_public'

### ISSUE THREAD

**Issue by StuartWhelan** [StackStorm/st2#2426]
During my testing and development I would like to restrict hubot to only use a couple of hipchat rooms.

This can be controlled using the hubot hipchat adapter settings called 'rooms and 'rooms_join_public' as seen in the following docker logs hubot output:

[Tue Jan 26 2016 00:55:48 GMT+0000 (UTC)] DEBUG HipChat adapter options: {"jid":"1_1215@hipchat.mydomain.com","password":"****","token":null,"rooms":"All","rooms_blacklist":"","rooms_join_public":true,"host":null,"bosh":{"url":null},"autojoin":true,"xmppDomain":"btf.hipchat.com","reconnect":true}

**Comment by emedvedev** [comment]
As a general rule we try to keep Hubot adapter-agnostic and avoid setting Slack-only or HipChat-only options. Room restrictions work differently in different adapters, so that's going to be tricky.
The best (and fastest) course of action, if you absolutely need this for testing and development, would be patching up your Hubot container manually, but if you have a more detailed proposal, we'll be happy to help!

**Comment by manasdk** [comment]
> As a general rule we try to keep Hubot adapter-agnostic and avoid setting Slack-only or HipChat-only options.

This is generally a good idea however in this case `Hubot` or the hipchat adapter itself has support for these so we would be a pass through. I guess since we started maintaining https://github.com/StackStorm/docker-hubot we sorta signed up to support this sort of adapter only pieces going forward. 

My vote is to support :)

**Comment by emedvedev** [comment]
Env variables are supported through `st2chatops.env` now, closing.
