### ISSUE TITLE
Changing system_user information in st2.conf requires restart

### ISSUE THREAD

**Issue by lanthos** [StackStorm/st2#2446]
A couple of times now I've run into an issue with troubleshooting my st2 setup due to my having gone and updated the system_user section of st2.conf and not having restarted.

Lakstorm on Slack has been helpful in troubleshooting this and suggested I open a bug for this as it's not optimal to have to restart st2 when you change the ssh key path in st2.conf.

**Comment by manasdk** [comment]
It is a quirk of how config is pre-loaded into memory and not always read from the filesystem. Perhaps we can use inotify to listen on config changes to and refresh the in-memory structures.

**Comment by Kami** [comment]
@lanthos Thanks for the report / suggesting.

@manasdk That would, imo, be a big overkill.

The system user change would be easy one, but a lot of other code is not designed to be reloadable / changeable without a restart. Designing everything for it is almost impossible and not to mention that we should embrace "everything should be restartable at any time" approach.

Imo, it's totally fine to require a restart as long as we document this (and requiring restart for everything, imo, is better than requiring restart for something and using SIGUSR1 or similar for other because of consistency reasons). There should be no impact as long as user is running StackStorm in a HA manner and they perform a rolling restart.

**Comment by lakshmi-kannan** [comment]
I see the point in making people always restart. Let me edit SSH troubleshooting documentation to add info about restart on config changes.
