### ISSUE TITLE
Unable to specify a proper cron syntax with st2 time rule.

### ISSUE THREAD

**Issue by lakshmi-kannan** [StackStorm/st2#2499]
See https://stackstorm-community.slack.com/archives/community/p1455477919006080

Reported by: @BurtonR on slack

**Comment by lakshmi-kannan** [comment]
@BurtonR is looking into this.

**Comment by BurtonR** [comment]
The good news is APScheduler does support the ability to pass expressions (not just int) to the cron timer as noted in the api docs: http://apscheduler.readthedocs.org/en/v3.0.5/modules/triggers/cron.html#expression-types

Now, to figure out how to add that level of validation to the timer trigger registration....

**Comment by codyaray** [comment]
+1

Our initial use case is all about converting cron jobs into centrally scheduled jobs. So we have lots of them (mostly using day_of_week: 1-5, etc). :(

**Comment by Kami** [comment]
I believe this PR should resolve this issue - #2579

We now allow user to specify strings for CronTimer trigger parameter values and use expressions such as `a-b`, `*/a`, `a,b,c`, etc.

**Comment by codyaray** [comment]
Hurray!

**Comment by Kami** [comment]
@codyaray Let me know when you had a chance to test those changes.

**Comment by codyaray** [comment]
Just realized this issue was still open. Tested more fully today for you. The new formats all look great!

I think we've discussed this before, but I still expect the `day_of_week` numbering to cause issues. The `day_of_week` numbers used by [apscheduler](http://apscheduler.readthedocs.io/en/latest/modules/triggers/cron.html#apscheduler.triggers.cron.CronTrigger) are all off by one from what most people expect for [cron entries](https://en.wikipedia.org/wiki/Cron). Also, I don't think `7` is supported but it is by a lot of crons. This is going to result in some confused users when things don't execute. (Plus I'm going to have to be extra diligent in helping my team "unlearn" this cron-ism).

All of these work beautifully: `a-b`, `*/a`, `a,b,c`, `a-b,c`.

* `day_of_week: thu`
* `day_of_week: Thu`
* `day_of_week: THU`
* `day_of_week: wed-fri`
* `day_of_week: mon-tue,THU`
* `day_of_week: 0-1,3`
* `minute: "*/5"`

I did notice that spaces aren't allowed, but I don't think they're allowed in normal cron either.

* `day_of_week: mon-tue, THU`
* `day_of_week: 0-1, 3`

Thanks for taking care of this!

**Comment by Kami** [comment]
You are welcome.

Both implementation seem to use `0-`6, but it seems like appscheduler starts with Monday and cron (at least what's described on Wikipedia) with Sunday. Is this correct and that's the inconsistency you don't like?

If so, I would need to do a bit more research to verify that most of the cron implementation indeed start with Saturday. If most implementations indeed start with Sunday I would be open to potentially changing our implementation as well. For backward compatibility reasons though, we would probably need to introduce some kind of per-installation or per-rule flag.

**Comment by codyaray** [comment]
> appscheduler starts with Monday and cron (at least what's described on Wikipedia) with Sunday. Is this correct and that's the inconsistency you don't like?

That sounds about right. Specifically, people tend to think `1-5` means all weekdays, Monday to Friday. I'm sure that we're going to see folks set `1-5` and accidentally get Tuesday through Saturday. Of course, I'll try to get them to just do `mon-fri` which avoids this whole mess. :)

**Comment by Kami** [comment]
@codyaray We could do a code change, but that change would be backward-incompatible so I decided to go with a documentation change to begin with - https://github.com/StackStorm/st2docs/pull/154

In case more people complain, we can revisit this decision and potentially change our `CronTrigger` `day_of_week` behavior to fully match the cron one.

I will go ahead and close this ticket, but as mentioned above, if you think we should change `day_of_week` behavior, please open a new ticket.

**Comment by codyaray** [comment]
Sounds good. Thanks for updating the docs at least. 

Actually had my first "customer" run into this issue over the weekend. I'll wait before I open to see how much push-back I get and if I can just push everyone to use `mon-fri` instead. :)

Thanks Kami!

**Comment by Kami** [comment]
You are welcome and keep us posted :)
