### ISSUE TITLE
Feature request: Timezones

### ISSUE THREAD

**Issue by murgurgula** [StackStorm/st2#2532]
It would be really usefull to be able to change the timezone from UTC to something else, matching the local time (example: Montreal GMT-5)
In case of an investigation, it's not so convenient having stackstorm time in UTC, while the rest of the servers (monitoring, config management, web servers, db, etc) are in local time.

**Comment by Kami** [comment]
First thanks for the feedback.

I do see some value in allowing users to configure default display timezone for the dates displayed in the CLI and web UI, but I think we should still default to UTC.

Non UTC might be OK if the whole team is located in the same timezone, but if you have people working in different timezones the best thing to do is to display everything in the timezone so there is no confusion.

As far as servers go - it's usually also best practice to have a timezone on all of the servers set to UTC (it has been a long time since I have seen a server which was not running on UTC).

**Comment by murgurgula** [comment]
I don't really care about the default being on UTC, I just want an option to configure the timezone to whatever I need

>it's usually also best practice to have a timezone on all of the servers set to UTC
This is not the case everywhere. Most servers I had to manage were configured with GMT-5, since the whole team and the customer is located in montreal.

Having 1 server to be set to UTC may lead to confusion in case if an investigation is needed and also, add additional time to it, since a person would need to sit & translate the time of the events to "local"

Currently, I do see the static timezone with no option to change as an inconvenience.

**Comment by Kami** [comment]
That's fair enough - I'm fine with making it a configuration option for the CLI and Web UI.

@enykeev how hard would be to do this in the web ui? Ideally, this would per client / user (and not global config option) so we would need to use cookie / local storage or similar.

**Comment by manasdk** [comment]
Yes. +1 on UI and CLI displaying in local timezones if configured.

@murgurgula Is the ask also for server logs and entries of timestamps in the DB to be in local timezones?

**Comment by Kami** [comment]
@manasdk For what is worth, I'm definitely -1 on storing non-UTC timestamps in the DB. Timestamps should always be stored in UTC and re-calculated to the requested / local timezone on display, if needed.

And not to mention that this doesn't really matter since in a lot of places we actually store timestamp as a unix epoch.

**Comment by murgurgula** [comment]
@manasdk 
@Kami 

I don't know about the timestamps in the DB. What I need is to be able to see which action happent on what time on the CLI  & interface with the local timezone.

For example, I want "st2 trigger-instance list" to display " Fri, 26 Feb 2016 11:25:17 GMT-5" in the "occurence_time" field.

I don't really see myself going to the DB to get data manually other than in a really strange debug case.

**Comment by Kami** [comment]
@murgurgula Yep, thanks for clarifying it. That's CLI and Web UI and we are fine with adding a configuration option there.

**Comment by Kami** [comment]
Here is an initial, work in progress support for display timezones for the CLI - #2537.

**Comment by Kami** [comment]
I've merged #2537 into master so I will go ahead, close this ticket and open one in st2web.

**Comment by lingfish** [comment]
I know this is closed, but I just wanted to 100% disagree with:

> As far as servers go - it's usually also best practice to have a timezone on all of the servers set to UTC (it has been a long time since I have seen a server which was not running on UTC).

In my "25+ years of Unix" opinion, this is _not_ best practice at all.  Best practice is to run the system clock as UTC (BIOS usually), and then usually the OS timezone set locally as well.  If not done in OS, the user then decides via TZ= etc (the only downside to local user-chosen TZ is of course, most logs still output in OS set timezone.)
