### ISSUE TITLE
[Errno 7] Argument list too long

### ISSUE THREAD

**Issue by emptywee** [StackStorm/st2#2599]
Hello,

Getting this when passing huge results from one task to another. Any way to work around it?

```
[Errno 7] Argument list too long
  File "/usr/lib/python2.7/site-packages/st2actions/container/base.py", line 98, in _do_run
    (status, result, context) = runner.run(action_params)
  File "/usr/lib/python2.7/site-packages/st2actions/runners/localrunner.py", line 150, in run
    kill_func=kill_process)
  File "/usr/lib/python2.7/site-packages/st2common/util/green/shell.py", line 81, in run_command
    env=env, cwd=cwd, shell=shell, preexec_fn=preexec_func)
  File "/usr/lib/python2.7/site-packages/eventlet/green/subprocess.py", line 53, in __init__
    subprocess_orig.Popen.__init__(self, args, 0, *argss, **kwds)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
```

**Comment by Kami** [comment]
This is a known limitation on Linux - there is an upper limit for a total size (in KB) of arguments you can pass to a process via the command line.

Work around for this is to save really large results in a datastore.

**Comment by Kami** [comment]
Sorry, I accidentally closed the issue.

One of the possible long term solutions for us would be to pass parameters / arguments to the Python runner action process via stdin instead of via command line arguments, but this has some other issues / limitations (it makes it more opaque and harder to debug actions manually, etc.).

In the short term, we will probably document this behavior and intercept this exception and throw a more user-friendly one which points user to the documentation which describes the aforementioned work-around.

**Comment by emptywee** [comment]
I know about the limitation on a command line argument in Linux. However, it's a large field to discuss. Can you use some sort of IPC, or perhaps a message broker, or Redis for example. With proper logging it should be not a big issue to debug/troubleshoot.

**Comment by Kami** [comment]
Yeah, there are many possible approaches to solving this, but the idea behind command lines arguments was to make it transparent and easier to debug in ,the standalone mode.

You lose a lot of direct visibility if you use some kind of message queue so if anything, I would prefer to go with stdin approach.

**Comment by lakshmi-kannan** [comment]
Related: https://github.com/StackStorm/st2/issues/1598

**Comment by emedvedev** [comment]
Closing in favor of #1598
