### ISSUE TITLE
Feature request: SSH keys in rules = path or output of command.

### ISSUE THREAD

**Issue by murgurgula** [StackStorm/st2#2662]
It would be nice to be able to write the path or be a result of a command like $(cat /path/to/file) in the StackStorm Rules instead of writing the actual key 
Reason: 
- Make the config more readable.
It would be easier to see if the proper key is used.

- Reason for "result of a command"
Plug stackstorm to Vault or another system destinated to manage credentials.

**Comment by Kami** [comment]
Thanks for the feedback.

The reason why we have decided to go with the actual key content and not path is because action runner which executes actions can be deployed on many different servers. If we went with the path approach, you would need to ensure the key file is located in the same location on every server where action runner component is running.

One option for you would be to save the raw key content in the datastore and reference this datastore value in the rule. Right now we are also working on improved support for secrets in the datastore - we will allow you to encrypt secret values in the datastore and this will make datastore more suitable for storing secrets like that.

As far as result of the command goes - you can achieve that today by using a workflow - one action talks to vault or similar and then you pass this action's result to another action (in fact, that's what some of our users already do today).

Allowing user to execute arbitrary code or similar in rules would change the whole (security) model and of rules and that's something you can already achieve today using workflows and actions which were designed specially for that. You can see more background on why I don't think this is a good fit for rules in my comment on this issue - https://github.com/StackStorm/st2/issues/2654.

**Comment by murgurgula** [comment]
I understand, but having the private key in a rule is a security issue.
Rules, custom packs, etc most likely are stored in git. In a company, where infra is split (you do windows, I do linux, bobby takes care of the mail servers, Teddy is the network guy, etc), git may be in the control of someone else and having the keys in there may not be that suitable.

If it was a path the sysadmin would have to worry only about securing the actual key file, however, when the content of the actual key is spread across numerous files, it will become hard to track.

Is it hard to do both options?

**Comment by Kami** [comment]
@murgurgula Yes I agree that this approach is not ideal.

We could support both (also support path to the key file and document limitations of that approach - key needs to be deployed on all the servers, etc.), but I'm not too sure this will still be needed once support for encrypted datastore values is in place.

**Comment by murgurgula** [comment]
Not for someone who wants security, I would prefer encrypted datastore.

**Comment by Kami** [comment]
This has been resolved by #2668 and it will be included in the next stable release. Closing.
