### ISSUE TITLE
Feature Request: action.concurrency.attr that will cancel instead of delay

### ISSUE THREAD

**Issue by JohnWelborn** [StackStorm/st2#2794]
There are situations when I want to cancel a duplicate action instead of just delaying it.

This could be in the form of an optional parameter for the policy that would let me pick delay or cancel as the action to perform.

A workaround is to have an initial task that will see if the workflow is needed before running.

Examples:

Two users requests the same thing, but the workflow is already running because of the first request.

If an problem alert is triggering a workflow and it fires once per minute but the workflow takes a few minutes to fix the problem.

**Comment by Kami** [comment]
Thanks for this feature request.

I think this is quite a reasonable request. We could add `operation` attribute to the policy with a valid options of `delay,cancel` and for backward compatibility, default it to `delay`.

The code change should also be relatively easy.

**Comment by andrew-regan** [comment]
👍 Have some uses for this functionality as well!

**Comment by Kami** [comment]
Here we go - #2817

**Comment by codyaray** [comment]
@Kami I really like this change. This is what I've been asking about for cron jobs too. :)

Wonder if we could simplify the cron hacks we have right now to use it instead. (All our crons are currently workflows which first acquire a zookeeper lease to determine which node in an HA setup "wins" the action execution).

Let's role play a couple scenarios here.

Scenario 1: concurrent policy is cancelled
- action instance 1 triggered at 10:00:00.000
- action instance 2 triggered at 10:00:01.000
- action instance 1 completes at 10:00:01.200
- action instance 2 triggered at 10:00:01.350

Scenario 2: semi-concurrent policy executes twice
- action instance 1 triggered at 10:00:00.000
- action instance 1 completes at 10:00:00.200
- action instance 2 triggered at 10:00:01.000
- action instance 2 triggered at 10:00:01.350

Will Scenario 2 actually work out like this? Would it be possible to extend this to limit concurrency to a certain rate? For example, we could add a variable that represents how often its allowed to run or how long of a period to be considered "concurrent".

The way this works with our zookeeper setup is effectively we set the lease to expire in 30 seconds. This means we can't run a cron action more frequently than 30 seconds (which is fine since cron itself is one minute granularity) but also means we have a huge window for clock skew (ptp so not much) and stackstorm execution delays (more likely).

**Comment by JohnWelborn** [comment]
I've applied this as a patch to 1.5 and its working, Thanks!

Now I'm wanting to have a concurrency delay across all workflows that share the same attr. (Only one running workflow per server) :)
