### ISSUE TITLE
Inconsistent behavior from st2 execution list with -n flag

### ISSUE THREAD

**Issue by johandahlberg** [StackStorm/st2#2806]
Setting `-n 0` does not list all executions. See discussion in: https://github.com/StackStorm/st2/pull/2803

```
usage: st2 execution list [-h] [-t TOKEN] [-j] [-n LAST] [--action ACTION]
                          [--status STATUS]
                          [--trigger_instance TRIGGER_INSTANCE]
                          [-tg TIMESTAMP_GT] [-tl TIMESTAMP_LT] [-l]
                          [-a ATTR [ATTR ...]] [-w WIDTH [WIDTH ...]]

Get the list of the 50 most recent action executions.

optional arguments:
[...]
  -n LAST, --last LAST  List N most recent action executions; list all if 0.
[...]
```

**Comment by Kami** [comment]
To get back to the comment in https://github.com/StackStorm/st2/pull/2803#issuecomment-231974048.

I just had a look and if you don't provide a limit or provide a value which is > 100, you will get back a maximum of 100 items since this is the value for the max limit.

Same goes if you specify 0 for limit - you get back last `100` executions

As discussed in the other ticket, I will make this value user-configurable in st2.conf, but default it to 100 for safety and backward compatibility reasons.

**Comment by Kami** [comment]
@johandahlberg #2832 should work for your use case, right?

And of course updating the argument comment (removing "list all if 0").

**Comment by johandahlberg** [comment]
@Kami It looks like it should work for us. Thanks!

**Comment by Kami** [comment]
You are welcome and glad to hear it.

(#2832 has been merged into master)
