### ISSUE TITLE
Request for sort ordering execution list results

### ISSUE THREAD

**Issue by bri365** [StackStorm/st2#2837]
Allow users to specify sort order when requesting a list of executions.

When troubleshooting slow/overloaded systems, getting the oldest action/workflow in a given state is very helpful, especially as the API will only return a limited number of executions, so finding the oldest running action can required going directly to mongo.

Perhaps '-r' or '--reverse' for oldest to newest?

**Comment by Kami** [comment]
I believe API already supports that. In case it doesn't, it should be easy to add support for it (just need to update a class variable on the API controller class).

Same goes for CLI - should be quite easy to add support for a new flag. Do you want to take a stab? :)

In any case, I'm fine with "-r" flag (if it's not already used for something else). Otherwise perhaps `--sort desc/asc`.

**Comment by bri365** [comment]
I'll drop it in my queue :-)
