### ISSUE TITLE
Rule - `st2ctl reload` Reloads all except rules

### ISSUE THREAD

**Issue by vaishalipavashe** [StackStorm/st2#2861]
- Intervaltimer rule was created and tested. Tried disabling it by updating rule yaml file and reloaded st2ctl as `st2ctl reload` but still rule is enabled:

![image](https://cloud.githubusercontent.com/assets/10110869/17563463/7e2da484-5efd-11e6-9e4e-d3015a31c859.png)

- From `st2ctl reload` output found that it reloads all except rules. Performed `st2ctl reload --register-rules` to reload rules and now it shows disabled:

![image](https://cloud.githubusercontent.com/assets/10110869/17563523/d66f35b8-5efd-11e6-9625-91cbcb3a4e70.png)

**Comment by armab** [comment]
Yeah, you have to `reload` with `--register-rules` manually.

This is something that Manas described previously in https://github.com/StackStorm/st2/issues/1619#issuecomment-111215415

The reason is that different `packs` can contain default rules and it's safer for administrator not to load them.
If all rules are registered - then you have many triggers enabled, running different actions (which most of us probably don't want).

@kami will correct me if I'm wrong.

**Comment by armab** [comment]
I think there is definitely a user & usability problem here, since it's something that raised many times.

The good approach for me feels like: 
- pack install should load all content within a pack (and not load everything else, out of current pack scope)
- there should be ability to (re)load files for specific pack (isolated)
- make the interaction interface easy for users/predictable/obvious

**Comment by samirsss** [comment]
Isn't it the users responsibility to make sure that the rules they want to not trigger be saved in disabled state? 

I think this ask is a fair thing. I'm getting used to the system and I didn't realize that the 1 rule I had written up didn't get reloaded when I did st2ctl reload. (it wasn't an important rule) but still the expectation that I had was rules would get reloaded.

@lakshmi-kannan @Kami

**Comment by Kami** [comment]
Yeah the idea behind rules being disabled by default was that unlike actions, rules are usually not totally generic and they need to be modified / customized by the user before they can be used.

That's why we decided not to register rules by default - if user didn't modify the rule or disable it, they would get surprised.

**Comment by samirsss** [comment]
Then should we close this PR? I dont have the history on this and hence just thinking from users perspective.

**Comment by Kami** [comment]
We can all think about it some more about re-evaluate our decision aka if we still think that's the best default behavior.

/cc @lakshmi-kannan

**Comment by lakshmi-kannan** [comment]
I think arma nailed it here: https://github.com/StackStorm/st2/issues/2861#issuecomment-238956012

st2ctl reload IMO should register rules by default. This has caused user frustration. We just have to make sure we don't ship dumb rules in enabled state with the product. If users place their rules on disk, it becomes their responsibility. 

I thought manas added st2 rule enable/disable. st2 rule list --disabled and st2 rule list --enabled are things we can build for better visibility.

**Comment by Kami** [comment]
>  We just have to make sure we don't ship dumb rules in enabled state with the product. If users place their rules on disk, it becomes their responsibility.

Agreed.

**Comment by samirsss** [comment]
So in summary we think its good to register rules as part of st2ctl reload. 

Yes there is a --enabled --disabled flag in the st2 rule list command.

**Comment by vaishalipavashe** [comment]
Rules from `examples

**Comment by Kami** [comment]
it's good that we have re-evaluated that decision.

@samirsss if you feel like it you can make the change so rules are registered by default and everything which goes along with making a change (code changes, changelog entry, documentation entry, upgrade notes entry, etc.).

**Comment by samirsss** [comment]
Yep i can do it...

**Comment by lakshmi-kannan** [comment]
Seems like the fix went it. Closing.
