### ISSUE TITLE
Workflow execution history displays secrets from st2kv() in plaintext

### ISSUE THREAD

**Issue by cbrenton** [StackStorm/st2#2915]
When running a workflow that pulls in a secret from `st2kv()`, there is currently no way to obfuscate that value if it's used in a non-secret field. This creates an issue where we are unable to use secrets in certain workflows without them showing up in logs. It would be nice to have a way to obfuscate this data, whether that's a way to flag a workflow execution as secret, a way to temporarily mark an action parameter as secret (as opposed to permanently via `config.schema.yaml`), or something else entirely.

Attached is a screenshot of a problematic workflow execution - note that the password (grabbed from `st2kv()`) appears in the logs (blanked out in red). Without marking `core.local`'s `cmd` param as secret (and making us unable to rerun any `core.local` executions), we can't hide this data from the logs. This data shows up both in the web ui and the output of `st2 execution get`.

![webui_history_st2kv_encryped_value_cleartext](https://cloud.githubusercontent.com/assets/609595/18649045/3b590326-7e72-11e6-8db9-f6c9144539f2.png)

**Comment by m4dcoder** [comment]
This occurs when the st2kv() is used as input args to a mistral task. The kvp gets resolved first before passing the value as input args to st2 for execution. Therefore st2 in this case has no idea that the input arg came from a secret kvp. A workaround is to use jinja for the kvp resolution (i.e. {{ system.foobar }}) where the key doesn't get resolved to the value until the action is being executed by st2.  The web UI will shows the jinja expression instead of the actual value.
