### ISSUE TITLE
An action is not cancelled, nor is marked as cancelling

### ISSUE THREAD

**Issue by ab9-er** [StackStorm/st2#3029]
Cancelling a task via st2 interface does not give any information about the state of the operation. Apart from a single popup that says the cancellation is requested, nothing else is displayed.

Via the CLI, once the cancel is requested it takes a huge amount of time to cancel the task. Sometimes even an hour. Repeated cancelling results in an error that says the action is already marked as cancelling but executing action list shows the action as running.

**Comment by ab9-er** [comment]
Api logs
```
2016-11-16 15:26:48,200 140490949332016 INFO hooks [-] 971a6669-8a4d-4218-b100-a3628da3138a - DELETE /v1/executions/582c5e048f97dc1759580a80 result={
    "faultstring": "Action cannot be canceled. State = canceling."
} (result='{\n    "faultstring": "Action cannot be canceled. State = canceling."\n}',request_id='971a6669-8a4d-4218-b100-a3628da3138a',status_code='200 OK',remote_addr='127.0.0.1',path='/v1/executions/582c5e048f97dc1759580a80',method='DELETE')
```

**Comment by armab** [comment]
This Issue was originally reported in #community: https://stackstorm-community.slack.com/archives/community/p1479308097002964

Symptoms:
- `CLI` is just freezing on `st2 execution cancel`

Also, from the Chat: MongoDB size is not big: `st2        0.953125GB`


I think we definitely need more info: 
- `st2` version
- `OS`, installation method, CPU/Memory resources available
- `tail -f /var/log/st2/*` during command execution
- some examples to reproduce, is it reproducible every time for specific action or not, more symptoms and debugging information

Also running st2 services in debug mode (and showing logs) https://docs.stackstorm.com/troubleshooting/debug_mode.html#enabling-debug-mode might help to understand the nature of issue better.

**Comment by lakshmi-kannan** [comment]
cc: @Mierdin
