### ISSUE TITLE
Some concept of inventory/hosts mapping/host database/host structure

### ISSUE THREAD

**Issue by harlowja** [StackStorm/st2#3172]
Most commands take some kind of host list, but its pretty uncommon (or what I feel) to have to have people individually list out those hosts because well most people have host lists or databases and structure elsewhere; so instead of requiring all this manual selection and specification of all the hosts to run against it makes more sense to just integrate with some type of host listing system and get all the hosts from there instead.

**Comment by harlowja** [comment]
For comparison with ansible:

http://docs.ansible.com/ansible/dev_guide/developing_inventory.html

https://github.com/ansible/ansible/tree/devel/contrib/inventory

The fact that stackstorm doesn't have something similar == sad.

**Comment by Kami** [comment]
Thanks for this feature request.

I see some value in it but ultimately I think this is something which should be done outside StackStorm (e.g. by utilizing something like Ansible, consul, AWS inventory service or similar).

The reason for that is that StackStorm is designed to be event-driven automation platform and there are already many other projects and product which main purpose is to act as inventory management services. So instead of us "reinventing the wheel" I would prefer users to utilize existing projects for that.

Having said that, if we can come up with some kind of "lightweight" integration with those existing systems which doesn't require us to reinvent the wheel too much I would be fine with exploring that option...
