### ISSUE TITLE
curly bracket in action parameters

### ISSUE THREAD

**Issue by jthunt** [StackStorm/st2#3181]
I am currently running version 1.4 and looking to upgrade to version 2.1.

I have several custom actions I have created and one parses text from a string and provides the text back between a set of markers.  Very simple action.

So the action takes a parameter string of {{1341234}} and returns 1341234.  This currently works in 1.4.  

When I manually run the action is 2.1, I see the passed in string correctly in the parameter list. 

parameters:
  parsetext: Text {{12445}} Text

but when it's passed into the action in the run method on my python action script, those curly brackets are removed.  The text inside the brackets is still there though.

I confirmed this by printing out the value right after its passed to the run method.

Should I be escaping these curly brackets before passing them in now?

**Comment by Mierdin** [comment]
Sorry for the delayed response. And just FYI, 2.2.1 is out, and 2.2 includes a lot of changes to Jinja2, especially in Mistral workflows.

Anyways, all that said, I was able to replicate what you saw on 2.2.1. The reason this is happening is so that we can reference variables when passing parameters into actions - for instance, `st2kv` , for referring to stored K/V pairs in StackStorm.

So, if you are looking to do some similar replacement functionality in your action, you might need to use a different marker, something that StackStorm isn't going to mess with.

**Comment by lakshmi-kannan** [comment]
@jthunt Can you verify and get back to us?

**Comment by jthunt** [comment]
Sorry..   I coded around it.  Since I was using a custom sensor, I parsed out the fields in the sensor itself.
