### ISSUE TITLE
Default RBAC configuration does not allow use of st2 pack config

### ISSUE THREAD

**Issue by LindsayHill** [StackStorm/st2#3283]
Steps to reproduce:

1. Install new BWC system using one-line install. Note that RBAC is now enabled by default
2. Authenticate as st2admin
3. Install a pack - e.g. `st2 pack install zendesk` - this will succeed
4. Attempt to configure the pack with `st2 pack config zendesk`. Result: 500 Server error.

Output:
```
ubuntu@bwcxenial:/opt/stackstorm/packs/dcfabric$ st2 pack config zendesk
subdomain: bwc
email: lindsay@brocade.com
api_token (secret): ***************
---
Do you want to preview the config in an editor before saving? [y]: n
---
Do you want me to save it? [y]: y
ERROR: 500 Server Error: Internal Server Error
MESSAGE: Internal Server Error for url: http://127.0.0.1:9101/v1/configs/zendesk
```

This is an example of typical st2api.log output https://gist.github.com/anonymous/e71026f96062bb1f5c8f0eeae145de50

Wonder if there's a connection to https://github.com/StackStorm/st2/pull/3235 ?

**Comment by Kami** [comment]
Yeah #3235 should have fixed that.

Are they using v2.2.0?

**Comment by efenian** [comment]
Yes, v2.2.0, from what it looked like to me pack_config in API checks for PACK_CREATE permissions.  However, that permission is not in the resolver assert list:

https://github.com/StackStorm/st2/blob/master/st2api/st2api/controllers/v1/pack_configs.py#L82
https://github.com/StackStorm/st2/blob/master/st2common/st2common/rbac/resolvers.py#L339

If I change the line in pack_config.py to PACK_INSTALL instead of PACK_CREATE and then restart services then it seems to work for me.

**Comment by Kami** [comment]
@efenian Thanks again for confirming.

I just checked the code and I see the issue (similar to #3235, but a different issue). Will work on a fix shortly.
