### ISSUE TITLE
Feature Request - SSH Connection Caching/Multiplexing

### ISSUE THREAD

**Issue by nmaludy** [StackStorm/st2#3291]
It would be great for the performance of SSH heavy workflows if the SSH connections were cached and could be re-used. Theoretically even across action runs.

https://en.wikibooks.org/wiki/OpenSSH/Cookbook/Multiplexing

I use this myself in terminal sessions by having the following in my ~/.ssh/config
```
Host *
  ControlPath ~/.ssh/controlmasters/%r@%h
  ControlMaster auto
  ControlPersist 10m
```

When i ssh into a server a socket file is created in ~/.ssh/controlmasters . This socket is reused on subsequent ssh connections, _drastically_ reducing connection time. This socket is kept open until it is idle for 10 minutes, then it is closed. 

I know Ansible makes use of this same functionality to help speed up its runs.

A recent bug was fixed https://github.com/StackStorm/st2/issues/3274 that cleaned up dangling connections. Is there was a way to create a cache of these connection objects so they could be re-used? 
 Also not sure about thread safety?

**Comment by bigmstone** [comment]
@nmaludy This is a difficult problem to solve for us since a lot of state needs to be shared between multiple `actionrunners` - which could exist on multiple servers. We also use paramiko for ssh connections so we'd have to build that atop the existing structure.

Given the complexity I would imagine the "easiest" thing to do would be to create a different ssh runner to handle persistent connections with subscribed connection handlers that can persist connections for reuse and block when currently in use. This would be a big undertaking and I'm not clear on how much of an advantage it would bring.

I might be overlooking something though so I welcome comments from other members of our team.

**Comment by nmaludy** [comment]
Throwing out some ideas here...

1) Delegate these commands to an Ansible playbook with properly configured openssh ControlPath. Then, Ansible would handle the connection caching.

2) Create another runner type, as you suggested, that utilizes the native ssh command on the host with properly configured connection cache settings passed in on the command line or in a stackstorm controlled config file. This way the normal openssh controls will be handling the connection cache. Since OpenSSH is implemented in C this may prove to be a much more efficient solution than using the pure-python Paramiko library anyhow (to be measured).

**Comment by bigmstone** [comment]
@nmaludy Both of those would work for single systems installs (at least single system for action-runner). I was trying to think of a system that wouldn't break the scale model ST2 has.

It's possible this could be tied in with #3096 where sessions can persist on the originating action-runner and we route to that action-runner via some metadata. Needs some more thinking.
