### ISSUE TITLE
Ports for api and authentication services can't be changed

### ISSUE THREAD

**Issue by hagay3** [StackStorm/st2#3356]
Hi,
I'm trying to change the port for authentication module with no luck, the port remains on '9100' .
After the change I did also st2ctl restart.

I tried to edit this section, with new port 9109
```
[auth]
port = 9109
host = 0.0.0.0
use_ssl = True
```

Stackstrom process still listens on 9100 port
```
tcp        0      0 127.0.0.1:9100          0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:9101          0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:9102          0.0.0.0:*               LISTEN
```

I checked also the api and it's the same issue.

**Comment by Kami** [comment]
To change listening ports on production installation (where installed using packages and services are managed by service manager and not running in a standalone mode), you need to change ports in the service manager files.

For example, for Ubuntu, that is in the upstart file - https://github.com/StackStorm/st2-packages/blob/master/packages/st2/debian/st2.st2api.upstart

Note to us: We should either document this or also utilize st2.conf when services are managed by a service manager.

**Comment by hagay3** [comment]
I'm not sure what you meant by saying
"services are managed by service manager and not running in a standalone mode".
What is exactly standalone mode?

**Comment by hagay3** [comment]
I still cant get how to change the port.
OS is Ubuntu 14.04

**Comment by armab** [comment]
@hagay3 For Ubuntu14, edit the upstart init file located at: `/etc/init/st2auth.conf`.
You'll find the port definition there.

When you're done with modifying, don't forget to reload upstart configuration: `sudo initctl reload-configuration` and restart your service.

Hope that answers your question.

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/community/p1492346619722875

**Comment by hagay3** [comment]
Thanks @armab it did the magic.
I still think the one conf file should utilize the port as it does in many other products (mysql, cassandra etc..)

**Comment by mbrannigan** [comment]
I was having this issue with CentOS 7 and fixed it this way:

1. Edit `/usr/lib/systemd/system/st2api.socket`
Change `ListenStream=127.0.0.1:9101` to `ListenStream=0.0.0.0:9101`

2. Reload systemd
`systemctl daemon-reload`

3. Reload st2api
`st2ctl restart-component st2api`

4. Check to see if it's re-bound
```ss -lnt | grep 9101
LISTEN     0      128          *:9101                     *:*
```

**Comment by armab** [comment]
Cross-linking related issue: https://github.com/StackStorm/st2/issues/2676

**Comment by nicholasamorim** [comment]
Yeah, this is a problem indeed. I wasn't lucky with setting up ST2 on the Swarm. Or rather.. I actually was but the complexity was too much.

So I decided to simply register ST2's services on Consul so that I can have dynamic DNS to use on `nginx upstream` section. So that if ST2 suddenly spawns on another server due to failure in the previous one, nginx would still route nicely. 

But it only binds to `127.0.0.1` making this impossible.

**Comment by luislobo** [comment]
This is still an issue.
@armab what would be the way to change those ports on an installation with Ubuntu 18.04?

**Comment by armab** [comment]
@luislobo You can find stackstorm systemd files via `sudo ls -la /usr/lib/systemd/system/ | grep st2` and modify them manually with the port numbers  there.

**Comment by nzlosh** [comment]
It's possible to use systemd generators to create the `.socket` file contents dynamically from `st2.conf`.

An update to `st2ctl` service restarts would be required to perform a `systemctl daemon-reload`.  This is needed to execute the generators to read any potential changes made to `st2.conf`.

This solution would mean `st2.conf` becomes authoritative for `st2api`, `st2auth` and `st2stream` for the bind and port configuration.  This would make configuration more intuitive for users. I expect it would resolve this issue as well as #686 and #2676, since all supported OS' are now based on systemd.

**Comment by armab** [comment]
@nzlosh That would be really nice indeed!

**Comment by luislobo** [comment]
Thank you @nzlosh for your PRs!
