### ISSUE TITLE
Improve st2ctl status

### ISSUE THREAD

**Issue by nmaludy** [StackStorm/st2#3373]
Couple of times now on Slack people have come in with problems with either mongodb or rabbitmq that are not immediately obvious when running st2ctl status.

I have a couple ideas of how to improve this output

- Show rabbitmq PID/status
- Show mongdb PID/status
- Provide a --verbose option that prints out `systemctl status <service>`  for each component

I'm willing to make these improvements and am open to suggestions other may have. Thoughts?

**Comment by armab** [comment]
Thanks for raising an issue before creating the PR.
We've considered before something like this.

Showing rabbitmq, mongodb, nginx and postgresql statuses in `st2ctl` is not what we want, since they're different services and StackStorm could be configured in HA way with DB/MQ as external clusters, running outside of the machine.

Talking about the `verbose` flag, - keep in mind that we officially support 4 platforms `EL 6`, `EL 7`, `Ubuntu Trusty` and `Ubuntu Xenial`, meaning you have to deal with 3 init systems: `SysV`, `upstart`, `systemd`.
So `systemctl status` will look nice only for `systemd` and makes no sense for other init systems with `service status` because we already show something like that in `st2ctl status`.

Hope that answers your question.

**Comment by nmaludy** [comment]
OK i'll close this for now, thanks for the feedback.
