### ISSUE TITLE
Mistral cancel to parent workflow doesn't ripple down to individual tasks. 

### ISSUE THREAD

**Issue by lakshmi-kannan** [StackStorm/st2#3442]
https://github.com/StackStorm/st2/pull/3375/files doesn't appear to have fixed the issue. 

Repro and logs
https://gist.github.com/lakshmi-kannan/493ce616a3c2f1278eaec0736fba5f2b

**Comment by m4dcoder** [comment]
@lakshmi-kannan When a mistral workflow is cancelled, it doesn't cancel tasks that is non-workflow. It allows tasks such as shell and python actions to reach completion. This is by design since action runner doesn't truly kill those actions on cancel. So the behavior you reported is expected. Also, PR 3375 which you reference here handles tasks that is sub workflow. So if a workflow A has a task that calls workflow B. if workflow A is cancelled, workflow B is also cancelled. But any non-workflow tasks will be left alone to reach completion. Hope this explanation helps you understand.
