### ISSUE TITLE
Missing st2reactor lib

### ISSUE THREAD

**Issue by johnarnold** [StackStorm/st2#3516]
Ubuntu 16.04

Following install instructions for apt-get install st2 st2mistral, etc.  Packages are installed and st2 cli commands work.

I'm actually running stackstorm in docker containers, just trying to get dev environment working so I can write a pack.   It looks like st2reactor lib is not available to the python interpreter.

How is this supposed to get installed?

**Comment by LindsayHill** [comment]
If you're using Docker, it might be easier to use our ST2 Docker images - see https://github.com/StackStorm/st2-docker

If you're having trouble locating libraries, make sure you're using the right virtualenv. ST2 uses a virtualenv for core functions (sourced with `source /opt/stackstorm/st2/bin/activate`).

Note that packs also have their own virtualenv, and their own requirements.txt

**Comment by johnarnold** [comment]
Update:
I found the "Run from source" documentation:
https://docs.stackstorm.com/development/sources.html

...and tried that path as well.  Found a couple things:

1. mongodb systemd service bring-up is broken, so "launchdev.sh start"  fails.
2. "run from sources" st2 and the dockerized st2 expect different ports, so you can't run mongodb in container and then st2 from source.
3. even after doing 'make requirements' and activating virtualenv, I still don't have st2reactor available in python.

I looked at the vagrant instructions, but since my dev environment is already in a VM and we already heavily use docker and virtualenv, I didn't want to add a snowflake requirement on vagrant.

Overall, the onboarding process for developing a Pack is pretty bumpy.   I'm happy to contribute to improving the documentation, but I need some help actually getting it working first so I know what to document.

**Comment by johnarnold** [comment]
Thanks @LindsayHill I am up to speed on st2-docker and can bring up the whole st2 stack that way., but that doesn't help me get the required st2* python libs available (e.g. in pycharm) so I can finish my pack.

Your tip on activating and referencing the virtualenv within /opt/stackstorm/st2/bin/  actually worked!  Thanks!

I'm not sure why that's not in the docs (or if it is, I couldn't find it).  Also not thrilled that using the virtualenv "from the source" instead of from the package does NOT work.

**Comment by LindsayHill** [comment]
> Also not thrilled that using the virtualenv "from the source" instead of from the package does NOT work.

Probably because the 'run from sources' approach is more aimed at core st2 development, rather than pack development. Normally for pack development you don't need to do much from a core libraries point of view, but it depends what you're trying to do, and how your development model works, what tooling you're using, etc.

Issues & PRs are of course welcome against github.com/StackStorm/st2docs. If there's anything there that needs clarifying, point it out with an issue, and/or submit a PR to clean it up. Input from 'new' people is important, because the core team already has their environment set up, so misses the things that might be harder for people just getting started.
