### ISSUE TITLE
infinite action executions hatched from one action

### ISSUE THREAD

**Issue by leoxhj** [StackStorm/st2#3536]
Dear support,

Not sure whether it is designed or maybe my python script has problem.
I wrote a simple workflow with two tasks, first task will invoke python script action which actually wait 600 seconds, and during workflow execution, I noticed the action is kept reproduced which from my understanding should not (should only one action execution?).
you can see from attached screenshot below:
![image](https://user-images.githubusercontent.com/3273433/27722199-a1bad6c0-5d98-11e7-81d6-2223f34e2593.png)

If I want to stop from mistral cli, I have to find out all those executions and update execution state one by one, then this action will stop.

```
# mistral action-execution-update 7b789642-c7c7-48a6-8c62-3cf99ea76172 --state=SUCCESS
# mistral action-execution-update 17c35914-008e-41fa-8de0-68b51944aeb2 --state=SUCCESS
```
....

sorry for my crappy English, hope you guys can understand.

attached code:
[leotest.zip](https://github.com/StackStorm/st2/files/1114205/leotest.zip)
st2 command:
`st2 run leotest.async wait_time=600`

st2 version: 2.3.0

**Comment by LindsayHill** [comment]
Hey @leoxhj don't worry, your English is fine. A lot better than my Putonghua.

I think the problem here is that your workflow is named `async`, and so is your async.py.

When you run `st2 run leotest.async`, it looks at `actions/async.yaml`. That tells it to run the workflow at `actions/workflows/async.yaml`. Task1 in the that workflow calls `leotest.async`.

The key here is that `leotest.async` is resolving to the *workflow*. It is never calling `async.py`. Instead it calls the same workflow again, resulting in that nesting behavior.

I recommend doing something like this:
* create a new action metadata file `async_action.yaml`. 
* Inside that metadata file, it should be a python action runner, and should call `async.py`, with an input parameter `wait_time`. 
* Update task1 in your workflow to call `leotest.async_action`

Does that make sense?

**Comment by LindsayHill** [comment]
@leoxhj hopefully the above makes sense. Re-open the issue if you need to.
