### ISSUE TITLE
'max_page_size' shouldn't limit CLI output

### ISSUE THREAD

**Issue by armab** [StackStorm/st2#3736]
Following the https://github.com/StackStorm/st2/issues/3708#issuecomment-328666287 consensus, CLI number of results shouldn't be limited based on additional `max_page_size` in `st2.conf`, - it makes no sense in context of CLI with no pagination.

At the moment users can't do `--last 1234` in CLI - it's limited to `100` via [st2.conf](https://github.com/StackStorm/st2/blob/74d05664112b65f8b5c7bbc889fcde966eb579fa/conf/st2.conf.sample#L27-L28).

Additionally, with the https://github.com/StackStorm/st2/issues/3735 where users could get _all_ the results via `--last -1`, ini setting becomes logically obsolete.

**Comment by Kami** [comment]
I still don't agree with this verdict and believe only admins / users with correct permission should be able to use "limit -1" aka return all results.

In that scenario, that setting makes sense.

**Comment by armab** [comment]
In future I hope that our CLI will return _all_ the results by default (`-1`).

You can look at Docker as a normal (healthy) example. In a wild, I didn't see that much CLI which limited the results this way by default.
With `50` per page and `100` max parental control limits we're bringing bad UX to users, including ourselves.

Possibility to DDOS the system via API endpoints shouldn't be a reason to set such draconian limits, - in reality it's easy to find how to overuse the system in many other ways.

**Comment by armab** [comment]
@Kami Alternative is to set `max_page_size` to `-1` in `st2.conf` by default.
This will optionally allow admins to adjust that `st2.conf` setting, _only if they really need it_.

**Comment by Kami** [comment]
I do agree that API limit is just one of many ways the system can be (ab)used, but this doesn't mean that because there are many other potential places, we should ignore it all together. It's just something we need to keep in mind and be conscious about through the whole platform.

> @Kami Alternative is to set max_page_size to -1 in st2.conf by default.
This will optionally allow admins to adjust that st2.conf setting, only if they really need it.

I would prefer default to be more reasonable (e.g. 100), but this could be a good compromise.

**Comment by nmaludy** [comment]
As an end-user and admin, i would really like the ability to "show all" for a given command on the CLI. Whether or not the CLI calls the API with paged results under the hood, i don't really care.

**Comment by Kami** [comment]
> As an end-user and admin, i would really like the ability to "show all" for a given command on the CLI. Whether or not the CLI calls the API with paged results under the hood, i don't really care.

I do agree that there should be an easy way for an admin to see all the resources.

> @Kami Alternative is to set max_page_size to -1 (no limit) in st2.conf by default.
This will optionally allow admins to adjust that st2.conf setting, but only if they really need it.

@nmaludy @armab I think that's a reasonable compromise.

I'm not 100% happy with it, because I think there should be a reasonable default limit, but it's a compromise after all and at least the option is there :)

**Comment by armab** [comment]
Addressed by https://github.com/StackStorm/st2/pull/3761 and https://github.com/StackStorm/st2/pull/3939

Users can use `--last -1` in CLI now to get ALL the possible results.
