### ISSUE TITLE
request: option to skip duplicates when importing apikeys

### ISSUE THREAD

**Issue by Inveracity** [StackStorm/st2#3748]
It would be neat if I could import apikeys without being concerned that a key might already exist. That way using configuration management tools to deploy stackstorm idempotently would be less of a bother.

current result:
```
$ st2 apikey load apikeys.yaml
ERROR: 409 Client Error: Conflict
MESSAGE: Tried to save duplicate unique keys (E11000 duplicate key error collection: st2.api_key_d_b index: key_hash_1 dup key: { : "<snipped>" }) for url: http://127.0.0.1:9101/v1/apikeys
```

suggestion:
```
$ st2 apikey load apikeys.yaml --skip-duplicates
key 'xyz' already exists - skipped!
```

thanks for your consideration

**Comment by sammic30** [comment]
Is there any temporary solution to this problem?

**Comment by LindsayHill** [comment]
Load the keys one by one and ignore 409 errors.

**Comment by sammic30** [comment]
Thanks Lindsay..... do you have any example of loading keys one by one. below is the content of my apikeys.yaml
```cat apikeys.yaml
-   created_at: '2017-10-06T21:11:26.351968Z'
    enabled: true
    id: 59d7f17e4ef1ee2f74b02fb3
    key_hash: dc3be4e1726727814d0795dfce892c5e3990b4d24df8f375681388f65208bd1e56b8ffc82e44851338d54c409348dcc071a5a765d3e29687ac357391f9d5f7fa
    metadata: {}
    uid: api_key:dc3be4e1726727814d0795dfce892c5e3990b4d24df8f375681388f65208bd1e56b8ffc82e44851338d54c409348dcc071a5a765d3e29687ac357391f9d5f7fa
    user: testu
-   created_at: '2017-10-11T20:58:43.800315Z'
    enabled: true
    id: 59de86034ef1ee6c2841586a
    key_hash: 8caa5698db9a19877ed531773c60cc2e4f4b3bcee84e938c6fe7eb14bc51a9a1649d56fc122b07adcd6cf3ff55542ec43943154d1a8818457969e3baa75ffcbc
    metadata:
        used_by: test_sensu
    uid: api_key:8caa5698db9a19877ed531773c60cc2e4f4b3bcee84e938c6fe7eb14bc51a9a1649d56fc122b07adcd6cf3ff55542ec43943154d1a8818457969e3baa75ffcbc
    user: testu
```

**Comment by Kami** [comment]
Would also be worth looking into the behavior of the existing `st2 key load` command.

I believe `key load` doesn't throw on existing key (it just updates it), so if that's the case, we should update `apikey load` to behave the same, if possible.

@sammic30 

Edit: Now that I think of it - it might have something to do with `apikeys.yaml` file - can you please mask your private key and gist it? Also, how did you retrieve / create contents of this file? It's likely that it doesn't contain the ID / PK and that's why it throws.

It's the same story with `st2 key load` if file doesn't contain id for each key.

**Comment by Kami** [comment]
Update - I looked into it and yeah, it indeed looks like an issue with `st2 apikey load` command.

It throws on load if a duplicate entry is found while it shouldn't throw to be idempotent and consistent with `st2 key load`.

I will make the corresponding change to make it work. Thanks again for reporting this.

**Comment by Kami** [comment]
@Inveracity @sammic30 I believe #3786 should resolve it.
