### ISSUE TITLE
How to parse result with dynamic key?

### ISSUE THREAD

**Issue by sumeetisp** [StackStorm/st2#3873]
I executing a remote_sudo action and following is the output,
```sh
id: 5a13d5d37052cf40e1025bba
action.ref: examples.mistral-examples
parameters:
  vm_name: master
status: failed
result_task: create_vm
result:
  10.236.220.135:
    failed: false
    return_code: 0
    stderr: ''
    stdout: cri-server5
    succeeded: true
start_timestamp: 2017-11-21T07:29:23.891776Z
end_timestamp: 2017-11-21T07:29:30.723630Z
```

From the above output how can i access `result."10.236.220.135".stdout` when `10.236.220.135` will keep changing according to the target on which the action is being executed?

I want to publish the stdout part in the result.

**Comment by sumeetisp** [comment]
version: '2.0'

examples.mistral-examples:
    description: A basic workflow that runs an salt command.
    type: direct
    input:
        - vm_name
    tasks:
        execute_cmd:
            action: core.remote_sudo
            input:
                cmd: "hostname" 
                hosts: "x.x.x.x"
                username: "********"
                password: "***********"
            publish:
                result: <% task(create_vm).result %>
                user: <% $.username %>
            on-success:
              - output_to_file
        output_to_file:
            action: core.local
            input:
                cmd: "echo '<% $.result %>'"


In the above example task execute_cmd is working but output to file is failing. I dont see any visible issue. Please help

Secondly i tried using <% task(execute_cmd).result.get($.hosts) %> but did not work.

**Comment by LindsayHill** [comment]
Looks like you're on the right lines with `<% task(execute_cmd).result.get($.hosts) %>`. It probably needs to be something like `<% task(execute_cmd).result.get($.hosts).stdout %>`.

See https://github.com/StackStorm/st2cd/blob/master/actions/workflows/st2_get_installed_version.yaml#L24 for an example.

I think the problem comes from how you're defining the `hosts` param. In the example I linked to, `hosts` is an input to the workflow. It could also come from a published variable somewhere else in the workflow.

But in your workflow you seem to be hard-coding the host value?
```yaml
            input:
                cmd: "hostname" 
                hosts: "x.x.x.x"
                username: "********"
                password: "***********
```
Is that passed into the workflow, or hard-coded? If it's hard-coded, then you could publish it as a variable. You could probably also just directly refer to it in your `result.get($.hosts)` section

**Comment by sumeetisp** [comment]
Yes it is hard coded. i tried publishing a hard coded value as 
publish:
  user: <% $.username %>

This doesnt work.  How sud a hard coded value be published?

**Comment by LindsayHill** [comment]
If it's hard-coded, you don't really need to publish it. You can just re-use that same value wherever you're referring to it. 

But if you want to only hard-code it in one place, then refer to it as a variable in other locations, you could do the same thing as the `init:` task in that example I linked to earlier. It run ` core.noop` action, and publishes variables.

**Comment by sumeetisp** [comment]
@LindsayHill  Thank you. This is my first workflow and i am trying out things. :)
