### ISSUE TITLE
Support to install .egg dependancies with Packs for the virtualenv

### ISSUE THREAD

**Issue by nbaillie** [StackStorm/st2#3877]
Is there any method to install a .egg from a http source. (for use in a pack)
by adding it to something like the requirements.txt (my understanding is that pip won't/can't install the .egg)

The Package that i want to use is normally installed from the device like:
`easy_install -Z http://xxx/downloads/aaaa.egg `

and its not available from any other sources as the idea is that the .egg matches exactly the software version on the hardware.

On my dev machine i have installed it directly in the virtualenv for the pack and all is good, but in production we are looking to use docker 1ppc and it is more of a challenge to manage manually in that way.

**Comment by LindsayHill** [comment]
Right now there's no easy way to do that, since `pip` won't install it, and the `setup_virtualenv` step is basically doing a `pip install -r requirements.txt`

I'm not sure what your best move is here. Since you're either building your own images or running custom scripts to add those packs, maybe add an additional step that does the egg install?

**Comment by DavidJohnGee** [comment]
It is entirely possible to push your dependencies in to a single package and push that to the PyPi production repository. 

Pip can then use that new package in the venv to satisfy your requirements. 

Thanks,

David
