### ISSUE TITLE
Add utility script which just setup virtualenvs for packs without DB/MQ connection

### ISSUE THREAD

**Issue by shusugmt** [StackStorm/st2#3912]
## Background

In docker-ized environment, there are some use cases that we would like to put all packs, configs and virtualenvs contents baked on the image. Usually `st2ctl reload --register-setup-virtualenvs` can be used to setup virtualenvs for packs, but this script cannot be used in `docker build` step because it requires connection to MongoDB and RabbitMQ which does not exist in the image build process.

## Suggested solution

I've made a sample script:
https://github.com/shusugmt/st2-docker-pack-prebuild-example/blob/master/setup-pack-virtualenv.py

It would be great if st2 could ship a similar script in `/opt/stackstorm/st2/bin` or somewhere appropriate.

Before I wrote this script, I've come up with a fairly quick solution that manually activates st2 virtualenv in the build step and then run `pip install` for each pack, but apparently there are some [platform managed dependencies for all packes](https://github.com/StackStorm/st2/blob/master/st2common/st2common/constants/pack.py#L84-L88), so I thought it is better to follow more _st2-ish_ way.

**Comment by armab** [comment]
:+1: 

At the moment it's not possible to `st2 pack install` during the Docker build stage, because it requires fully-ready st2 app with Mongo/Rabbitmq connections.

We'll need to take the following logic from the existing pack install fuctionality: 
- download pack in the 100% the same reproducible official way with:
  - version validation
  - settings in st2.conf, exchange index
  - pack versioning schema, git, from branch, multiple packs etc
- setup virtualenv for those packs

It's OK to ship that as a standalone script with st2 core, re-using existing pack install primitives so it won't need Mongo/Rabbit.

Ex:
```
st2-pack-setup-virtualenv \
  github \
  ansible=v1.2.3 \
  cloudflare=776b9a4 \
  https://github.com/emedvedev/chatops_tutorial=testing
```
as described in https://docs.stackstorm.com/packs.html#installing-a-pack
