### ISSUE TITLE
st2sensorcontainer is not running.

### ISSUE THREAD

**Issue by maddygoes** [StackStorm/st2#4011]
"st2ctl reload --register-all" lists that "st2sensorcontainer is not running." ... this means sensors won't work right ??

in the logs i can see
```
AUDIT access [-] Access granted to "sensors_container" with the token set to expire at "2018-01-24T05:04:39.725464Z". (username='sensors_container',token_expiration='2018-01-24T05:04:39.725464Z')
```
anyway, I can get this into working condition??

**Comment by LindsayHill** [comment]
What does `st2ctl status` report?

If st2sensorcontainer is not running, you can restart it with `sudo st2ctl restart-component st2sensorcontainer`. You may also want to look at the log file for that service (`/var/log/st2/st2sensorcontainer.log`) to see what is happening with it.

**Comment by maddygoes** [comment]
I did that and it restarted the process... but looks like (username='sensors_container',token_expiration='2018-01-24T05:04:39.725464Z') is not letting sensor to run...

any way I can reset this, means expiration date or auth key?

**Comment by Kami** [comment]
It looks like that the auth token used by sensor container process has expired.

We generate auth token which is used for sensor container purposes on sensor start up so as @LindsayHill has said, restart should do the trick (new token should be generated).

Can you please gist whole sensor container log file so we can see what is going on. The log line and date you posted is a bit confusing / don't make sense since it's almost a month old. Again, hopefully seeing the whole log file will clear things up.
