### ISSUE TITLE
Polling Sensor stops polling

### ISSUE THREAD

**Issue by parkerberb-nfv** [StackStorm/st2#4289]
##### SUMMARY

I have a polling sensor that has suddenly stopped polling. It is reported as up/active, but it is not being executed.

##### ISSUE TYPE
 - Bug Report

##### STACKSTORM VERSION
st2 2.8.1, on Python 2.7.5

##### OS / ENVIRONMENT / INSTALL METHOD
running on Centos 7.5, installed with the one line install

##### STEPS TO REPRODUCE
leave attached sensor running for a few hours.

You can see in the attached st2sensorcontainer.log that, at the end of the file, the example sensor is reported as up but has no output or execution.

[st2sensorcontainer.log](https://github.com/StackStorm/st2/files/2254299/st2sensorcontainer.log)
[example.py.log](https://github.com/StackStorm/st2/files/2254304/example.py.log)
[example.yaml.log](https://github.com/StackStorm/st2/files/2254305/example.yaml.log)

##### EXPECTED RESULTS
Polling sensor never stops polling

##### ACTUAL RESULTS
Polling sensor blocks indefinitely / dies / otherwise stops executing until restarted.

**Comment by Kami** [comment]
Thanks for reporting this.

We haven't encountered an issue like that before. From the log files it's really hard to say what is going on, because everything looks fine then it looks like sensor just stopped polling.

It almost looks like that sensor got "stuck" - is it possible that the request to the HTTP endpoint some how got stuck and never timed out and that's preventing the next poll to run?

I would try to explicitly pass `timeout=5` argument or similar to `requests.get` method and see what happens.

EDIT: Looking here http://docs.python-requests.org/en/master/user/quickstart/#timeouts, it indeed looks like it doesn't have a default timeout and it's possible for request to hang / block indefinitely if timeout is not specified.

**Comment by parkerberb-nfv** [comment]
Yes, adding a timeout to the requests makes this go away.

**Comment by Kami** [comment]
Great to hear that :+1:

**Comment by guzzijones** [comment]
I just want to say thanks for reporting this.  I just ran into the same problem.

**Comment by guzzijones** [comment]
from requests documentation:
```You can tell Requests to stop waiting for a response after a given number of seconds with the timeout parameter. Nearly all production code should use this parameter in nearly all requests. Failure to do so can cause your program to hang indefinitely:```
