### ISSUE TITLE
Make st2-self-check aware of missing modules

### ISSUE THREAD

**Issue by vincent-legoll** [StackStorm/st2#4311]
##### SUMMARY

The self-test script tries to run mistral tests despite mistral not being setup / installed.

##### ISSUE TYPE

 - Bug Report

##### STACKSTORM VERSION

```
$ st2 --version
st2 2.8.1, on Python 2.7.5
```
without mistral workflow engine

##### OS / ENVIRONMENT / INSTALL METHOD

Up to date centos 7

```
$ cat /etc/redhat-release 
CentOS Linux release 7.5.1804 (Core)
```

##### STEPS TO REPRODUCE

```yaml
sudo st2-self-check
```

##### EXPECTED RESULTS

Not running (and failing) mistral-related tests

##### ACTUAL RESULTS

[...]
```
Attempting Test tests.test_inquiry_mistral... ERROR!
Attempting Example examples.mistral_examples... ERROR!
Attempting Example examples.orchestra-examples... ERROR!
```
[...]

I think the `orchestra` thing is a similar issue...

**Comment by LindsayHill** [comment]
I am -1 on automatically bypassing checks if Mistral is not installed. If the user does not have Mistral installed, it is misleading to get a successful result from `st2-self-check`, since their system is **not** set up correctly.

I think it would be better to off CLI options for bypassing Mistral and/or Orquesta checks. Those checks are a separate section in the code, so it should be easy to add a way to bypass that section.

Want to start a PR?

**Comment by LindsayHill** [comment]
This commit https://github.com/StackStorm/st2/commit/667b301f93c0480679f978b2a5ea72fc8f778eb5 provides CLI flags for skipping Orquesta and/or Mistral tests.

I'm not happy with the way it works though. The default is to skip Windows, but to run Orquesta & Mistral workflows (since that is the current default). Sort of feels like the CLI flag names are wrong. Thoughts on a nicer way to do this? Or just not worry much about it?

**Comment by vincent-legoll** [comment]
I'd do all such flags in the same way, either as skip-something or do-something. Whichever you prefer, but keep a consistent UI.

**Comment by LindsayHill** [comment]
The problem is that I don’t want to change the current behavior. The default should be to run the Orquesta and Mistral tests, but not to run Windows tests
