### ISSUE TITLE
(Question) Why does DatastoreService inhibit from handling non system-scope value?

### ISSUE THREAD

**Issue by userlocalhost** [StackStorm/st2#4451]
##### SUMMARY
I want to handle user-scope encrypted value in the datastore from action through DatastoreService methods.

An use case is to get user defined values which are different at each users like account information to access to each integrated system from an action.

But a past patch(https://github.com/StackStorm/st2/pull/2731) [inhibits from getting non system-scope value](https://github.com/StackStorm/st2/blob/master/st2common/st2common/services/datastore.py#L115-L116).

There is no description and reference for that patch. So could you please tell me what kind of problem this patch tries to solve for, and whether that problem still exists?

Thank you.

##### ISSUE TYPE
 - Other

##### STACKSTORM VERSION
`3.0dev`

**Comment by Kami** [comment]
Right now user-scoped datastore values can only be used and accessed for actions which are scheduled via the StackStorm API.

The reason for that is that those are the only actions which have a user context attached to them. If an action is ran via the API, user is set to the user which is authenticated against the API.

If action is ran via rule or if you want to use user-scoped value inside a sensor, that won't work because there is a no concept of "user" in those scenarios (sensors and rule triggered actions run under StackStorm system user ``stanley``).

Can you please share in more details your use case aka where you want to use user-scoped datastore values?

**Comment by userlocalhost** [comment]
Thank you for your reply. I'm glad to hear the important points to use user-scoped value, especially the case that an action is run from rule by system user.

> Can you please share in more details your use case aka where you want to use user-scoped datastore values?

Yes. In our environment, the StackStorm integrates many infrastructure services which hss own authentication system. And StackStorm set account, named "st2", for each integrated system to the pack's configuration.

In accordance with the growth of the number of integrated systems and users, the next operation problems were happened.

### 1. It's hard to track who manipulates each integrated systems.
  There are a lot of operation logs by "st2" user for each integrated system. For example, once a wrong configured VM instance was found in vSphere, it's hard to find out who create it. We always dig into execution history of StackStorm. It takes much operation cost because the execution time of StackStorm and the time logged at integrated system doesn't match exactly. 

### 2. It makes a loophole of permissions.
  By using a common account for an integrated systems, all users can access them even though some systems don't permit to them. That prevents StackStorm from prevailing in our company.

---
To solve these problems, I repaired packs which are developed in-house to read not only common account from the pack's configuration but also read account which is registered at user-scope datastore to be able to access it by individual user account of it. And we will let user register account informations of their systems that user use through by StackStorm. Then, I want to abolish (or degrade permission of) common account gradually.

Now I did it by re-implement the methods of DatastoreService that gets around [this restriction](https://github.com/StackStorm/st2/blob/master/st2common/st2common/services/datastore.py#L115-L116).
But if any implementation and security problem may not happen, would I make a PR to deregulate it?

**Comment by Kami** [comment]
Can you please clarify how those executions are triggered - via rule or via trigger dispatcher by a sensor?

One approach which allows you to "preserve user information" is integration using webhook with an API key. Each API key is assigned to a specific StackStorm user so this way if you dispatch a trigger via webhook, this context will be preserved all the way to the action execution.

As far as being able to "dynamically" specify arbitrary user context inside an action and sensor - as mentioned above, we explicitly didn't allow that because of the potential security issues (e.g. if action / sensor is not designed correctly user A could read items from user B or similar).

One approach we could potentially go with is "opt-in" approach on a pack or action level.

For example, pack author puts special attribute in ``pack.yaml`` / action metadata file (``allow_datastore_user_scope_access: True``) and if that attribute is set, actions and sensors could also access datastore values for arbitrary users.

I personally think this is a good middle of the ground approach. It would be opt-in and we would of course very clearly document that this approach can have negative security consequences if not used correctly (e.g. if ``username`` value is dynamically passed to the action instead of being dynamically retrieved / set inside the action or similar).

Would that work for your use case?

/cc @lakshmi-kannan @m4dcoder @bigmstone

**Comment by userlocalhost** [comment]
Thank you for your reply and sharing API key.

> Can you please clarify how those executions are triggered - via rule or via trigger dispatcher by a sensor?

Most of our case, we utilize StackStorm through CLI (by execuing `$ st2 run <workflow>` command).

> we explicitly didn't allow that because of the potential security issues (e.g. if action / sensor is not designed correctly user A could read items from user B or similar).

Yes, I also strongly agree with this feature. The point that I argue that

1. Action can read their own user scope data transparently which is set by authenticated user that runs this action via CLI.
2. Action cannot read specific user scope data that is set by other user.
3. Action cannot read specific user scope data from non-authenticated (system) user.

And I checked [current implementation of DatastoreService](https://github.com/StackStorm/st2/blob/master/st2common/st2common/services/datastore.py#L94) never allows (2) and (3). So I think deregulation of [this](https://github.com/StackStorm/st2/blob/master/st2common/st2common/services/datastore.py#L115-L116) may not raise security problem as you mentioned, don't you?

My understanding of API key is one of a mechanism to authenticate StackStorm. API key is quote useful to execute action as an user from external service to StackStorm. 

Though, our requirement is not select the user-information of StackStorm but the one integrated system.

---
Let me get this straight.

I want to let StackStorm to to be able to read own user scope data from executed action that is run by only authenticated user via CLI.

| The way running an Action    | Read user scope data | Read system scope data |
|:----------------------------------------------:|:--------:|:-:|
| via CLI by an authenticated User               | (AsIs) x <br> (ToBe) o | o |
| via rule or via trigger dispatcher by a Sensor | x        | o |

For example, I want to implement an action to access `System-A` as below (Fig1).

![desc](https://user-images.githubusercontent.com/469934/49149899-aec5d700-f34e-11e8-96c2-e606623c14e1.png)

The algorithm of authentication with System-A is
1. trying to get account information from user-scope database.
2. trying to get account information from system-scope database.
3. trying to get account information from configuration of pack.
4. raising an exception of authentication.

I expect this action behaves like following.
(1) Action is executed via CLI by authenticated User-A, this accesses to System-A as User1.
(2) Action is executed via CLI by authenticated User-B, this accesses to System-A as st2.
(3) Action is executed via rule by system account of StackStorm, this accesses to System-A as st2.

I believe deregulation of [this](https://github.com/StackStorm/st2/blob/master/st2common/st2common/services/datastore.py#L115-L116) is the reasonable way to enable this.

### PS: about a feature to be albe to 'opt-in' approach
> One approach we could potentially go with is "opt-in" approach on a pack or action level.
> 
> For example, pack author puts special attribute in pack.yaml / action metadata file (allow_datastore_user_scope_access: True) and if that attribute is set, actions and sensors could also access datastore values for arbitrary users.

Thank you for sharing valuable information. But I couldn't find out [PackDB](https://github.com/StackStorm/st2/blob/master/st2common/st2common/models/db/pack.py#L35) property which is associated with `allow_datastore_user_scope_access`. Could you please tell me where this is implemented?

**Comment by bigmstone** [comment]
@Kami's opt-in approach was a proposal for how we might achieve what you're after, it does not exist today; however, I'm not certain if you need to get the user's credentials from the action itself. It might be adequate to feed them in as optional secret parameters depending on the integration. You'll likely know that action parameters are rendered using the `KeyValueLookup` and a python action renders in system scope only since it uses the `DatastoreService`, as you mention.

So let's take an integration that needs an API key. You could have each action have an optional secret parameter that renders from `st2kv` and fed into the integration's action. That action can then look and see if a key was provided, if not attempt to get one in the system scope, then if not attempt to pull from the config. This would functionally give you what you are asking (unless I'm mistaken) without the need to have the action itself needing to act on-behalf of the requesting user.

/cc @Kami for additional thoughts

**Comment by userlocalhost** [comment]
Thank you very much for telling the way to get key-value from Datastore via `st2kv`.
I apologize that I overlooked [this great feature](https://docs.stackstorm.com/datastore.html#scoping-datastore-items).

I think this is smarter and more reasonable way for getting registered value from datastore than what I insisted of. Because the processing to read Datastore value doesn't have to be implemented by getting it from `st2kv` at the parameters in action metadata.

But I can't get user scope value via `st2kv.user` like following (I confirmed that I can get system scope value through `st2kv.system`).
<img width="653" alt="2018-11-30 10 55 11" src="https://user-images.githubusercontent.com/469934/49264717-c017fc00-f492-11e8-8fc5-2cbe97168666.png">

This is the environment information that I checked.
<img width="406" alt="2018-11-30 11 26 50" src="https://user-images.githubusercontent.com/469934/49264746-e342ab80-f492-11e8-912b-ab96e61c8744.png">

And here is the result of executing action (`default.test_kv`) attaching `--debug` option.
https://gist.github.com/userlocalhost/75c96a94ed4519206be861a18fafbce1

Is this problem of the implementation? or wrong [description of this document](https://docs.stackstorm.com/datastore.html#scoping-datastore-items)?

**Comment by userlocalhost** [comment]
I found a past PR (https://github.com/StackStorm/st2/pull/3164) that changes the processing to render Jinja expression of {{ st2kv }} to datastore value.

As is mentioned [the comment in this PR](https://github.com/StackStorm/st2/pull/3164/files#r99279926), we need additional implementation to get user-scope value. So I made a PR (#4463) to be able to read user-scope value via {{ st2kv.user }} notation.
