### ISSUE TITLE
why rule Enforcement ID is null

### ISSUE THREAD

**Issue by daimazai** [StackStorm/st2#4453]
![image](https://user-images.githubusercontent.com/40518437/49001546-e9394380-f197-11e8-878d-b1f7cb73a6d4.png)

**Comment by Kami** [comment]
It could be an issue with a rule - e.g. rule criteria contains invalid syntax or similar. Your best bet is st2rulesengine service logs in ``/var/log/st2/`` directory.

Having said that, we included some improvements for that in v2.9.0 and v2.9.1 release so that information is now exposed in the WebUI (if execution was not triggered because the rule evaluation failed or some reason).

If you are not running v2.9.1 yet, I would suggest you to upgrade.
