### ISSUE TITLE
Pack version for bundled / system packs (core, linux, etc.) should match StackStorm version

### ISSUE THREAD

**Issue by Kami** [StackStorm/st2#4535]
Right now we don't ever update version attribute in ``pack.yaml`` for packs which are bundled with StackStorm packages (core, linux, etc.). which means it's hard to check if pack content on disk is pristine / has been updated.

See https://forum.stackstorm.com/t/upgraded-to-st2-2-10-1-from-2-7-and-dont-have-core-winrm-cmd/467/6 for an example issue.

I propose updating ``version`` attribute for all the bundled packs to match StackStorm version. This should work fine since StackStorm version is also a valid semver string.

This will require us to update our release workflows to automate it.

**Comment by nmaludy** [comment]
+1

Should the `st2` pack version match as well?

**Comment by Kami** [comment]
``st2`` pack is a bit unique and more similar to other StackStorm-Exchange packs since it's not bundled with StackStorm installation.

So until we bundle it, there is no pressure to have the pack version match StackStorm version.

**Comment by LindsayHill** [comment]
Agreed - I think automating this will be helpful

**Comment by cognifloyd** [comment]
Could the release automation also include notes in the changelog to say what has changed in the pack since the last version (even if the only thing that is changing is the version)?

eg:
https://github.com/StackStorm/st2/blob/master/contrib/chatops/CHANGES.md
https://github.com/StackStorm/st2/blob/master/contrib/core/CHANGES.md

I was curious to see a complete list of packs included with st2. So here's a list.

Packs bundled and installed with st2:
- [ ] [chatops](https://github.com/StackStorm/st2/tree/master/contrib/chatops)
- [ ] [core](https://github.com/StackStorm/st2/tree/master/contrib/core)
- [ ] [default](https://github.com/StackStorm/st2/tree/master/contrib/default)
- [ ] [linux](https://github.com/StackStorm/st2/tree/master/contrib/linux)
- [ ] [packs](https://github.com/StackStorm/st2/tree/master/contrib/packs)

Would the packs that are not installed by default with st2 also be versioned with st2?
- [ ] [examples](https://github.com/StackStorm/st2/tree/master/contrib/examples)
- [ ] [hello_st2](https://github.com/StackStorm/st2/tree/master/contrib/hello_st2) (<- is this for a tutorial somewhere?)

Then there's the st2 pack that is not bundled and would not be versioned with st2 (That makes sense as it works across multiple versions of StackStorm):
https://github.com/StackStorm-Exchange/stackstorm-st2

**Comment by Kami** [comment]
Initial PR is here - https://github.com/StackStorm/st2cd/pull/369.

In the future, we also need to decide how to handle ``st2`` pack. Perhaps we should move it back to the core (we've done this back and forth before)?

As far as the changelog entry goes - it's a bit harder to do, but possible.

**Comment by Kami** [comment]
Confirmed that this release process change is now working end to end - https://github.com/StackStorm/st2/commit/9a1351418c12de73734f41b51b02007644ee408d.

I will close this issue and a new one can be opened for improvements for non-bundled system packs such as ``st2``.

As far as changelog goes - I agree we should also keep that up to date, but this will be manual work which will need to happen when someone updates the bundled pack.
