### ISSUE TITLE
Event driven automation sample

### ISSUE THREAD

**Issue by kanusoni** [StackStorm/st2#4969]
Hi,

how we can write script in stackstorm to perform event driven automation.
like if we are sending message to hubot like AWS instance help so it should go to AWS portal and then create an instance and revert back to us.
Thanks.

**Comment by armab** [comment]
Hi @kanusoni. Thanks for you interest in StackStorm. 

Instead of using Github repository which is for bugs, issues and code, please try to ask your questions at StackStorm Forums https://forum.stackstorm.com/ or join StackStorm's Slack chat Community https://stackstorm.com/#community. You can also search StackStorm blog for HOWTO articles https://stackstorm.com/category/tutorials/ and there are some good hands-on tutorials: https://github.com/EncoreTechnologies/stackstorm-tutorial

Thanks!

**Comment by kanusoni** [comment]
@armab Thanks for your reply.
