### ISSUE TITLE
Orquesta sub-workflow always get stuck 

### ISSUE THREAD

**Issue by hgjsj** [StackStorm/st2#5275]
One of orquesta sub-workflow alaways get stuck after scheduled.

Version is v3.4.1 running on RHEL 7

![image](https://user-images.githubusercontent.com/56862131/120149437-4bb5a380-c21c-11eb-89d9-cd7f2c8f4817.png)

In the chart, orqusta sub-flow is scheduled at 03:35:12UTC with running status, but the first action running at 03:43:12UTC, there are more than 8 minutes pending here.  Seems there is no other oquesta flows like this on my st2 , only this one has such issue.  

I checked st2scheduler.log, st2actionrunner.log and st2workflowengine.log, there is no excetion and error during this subflow execution. 

Do you have any suggestion how to identify problem? and what need I pay more attention when developing orquesta workflow? 

Thanks!

**Comment by blag** [comment]
I think "slow" is a better word to describe this. The word "stuck" would seem to indicate that the sub-workflow never gets executed, which isn't the case based on your screenshot.

There are some performance improvements that have been added since ST2 v3.4.1, and version 3.5.0 should be out in a few weeks. You can either try an unstable build (built nightly), or a build from unstable-staging (built on every merge to `master`), or you can wait to see if version 3.5.0 improves this for you.

**Comment by hgjsj** [comment]
Thnaks for your reply. This issue temp fixed after splite this oquesta flow to two, the waiting time decrease to a minute. Probably old flow has too much “when” statements and each branch published many variables, this made engine crazy. Looking forward to addressing performance in new version.

**Comment by syz951127** [comment]
> 

st2 3.5.0, on Python 3.6.8 
I have the same problem

**Comment by yogeshgoyal26** [comment]
@hgjsj and @syz951127 Seems the issue is same as the one fixed as part of change https://github.com/StackStorm/orquesta/pull/239, which is part of st2 3.6.0, Can you try with 3.6.0

**Comment by hgjsj** [comment]
@yogeshgoyal26  Already upgraded to v3.8.0. Performance has bigger improvement than 3.4.1, thank you.
