### ISSUE TITLE
st2 execution list cmd doesn't work as expected

### ISSUE THREAD

**Issue by anurag-bug** [StackStorm/st2#5350]
## SUMMARY
```
st2 execution list -n 1
```
doesn't work

### STACKSTORM VERSION

st2 3.5.0, on Python 3.6.9

##### OS, environment, install method

Docker on MacOs Catalina Following the quick start guide.

## Steps to reproduce the problem

Just run this command after authentication 
```
st2 execution list -n 1
```

## Expected Results

Last Execution 

## Actual Results
```
ERROR: HTTPConnectionPool(host='127.0.0.1', port=9101): Max retries exceeded with url: /v1/executions/?limit=1&parent=null&sort_desc=True&include_attributes=id%2Caction.ref%2Ccontext.user%2Cstatus%2Cstart_timestamp%2Cend_timestamp (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9b45c3b780>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by minsis** [comment]
The error `[Errno 111] Connection refused` is pretty self explanatory. The st2client is unable to connect to your st2web container.

* Whats the quick start guide you used?
* Is the st2web container running?
* Are you running inside the st2client container?
  * If you're running outside st2client did you set the ST2_*_URL environment variables and/or set the url params inside ~/.st2/config?

In the end the issue here isn't StackStorm, its that your client is unable to connect to StackStorm for some reason.
