### ISSUE TITLE
ST2 garbage collector is not cleaning up records in task_execution_d_b 

### ISSUE THREAD

**Issue by sravs-dev** [StackStorm/st2#5525]
## SUMMARY

Garbage collector is not cleaning up records in task_execution_d_b 

### STACKSTORM VERSION

st2 3.5.0, on Python 3.6.8

##### OS, environment, install method

Issue is related to DB

## Steps to reproduce the problem

Show how to reproduce the problem, using a minimal test-case. Make sure to include any content
(pack content - workflows, actions, etc.) which are needed to reproduce the problem.

Set garbage collector conf to remove all action execution records after X days. You can see that records in task_execution_d_b are not getting cleaned up as per the GC setting

## Expected Results

St2 DB should not have records older than the TTL set in st2.conf. 

## Actual Results

taskexecution_d_b is not cleaned up leading to GBs of stale data in DB and causing perf issues 

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by armab** [comment]
Thanks for the report.

So the `task_execution_d_b` is left unclened. But do you see the other history records are cleaned? eg. if the garbage collector works at all.
Could you also attach the logs from the garbage collection service?

**Comment by armab** [comment]
Found that the issue was raised in the past: https://github.com/StackStorm/st2/issues/4939.
And there was a PR which wasn't finished yet: https://github.com/StackStorm/st2/pull/4924

@sravs-dev If you'd like to continue the effort of finishing the feature in a fresh new PR, - that would be awesome! Looks like the majority of the implementation is there #4924.

**Comment by cognifloyd** [comment]
#4924 was just merged in #5605, so this will be available in 3.7.0
